'use client';
import {useMemo,useState} from 'react';
const YEAR=2026,MONTH=8;const firstDay=new Date(YEAR,MONTH,1).getDay();const daysInMonth=new Date(YEAR,MONTH+1,0).getDate();const weeks=Math.ceil((firstDay+daysInMonth)/7);
const projects=[{name:'10월 가을 선물',range:'09.17 - 09.30',progress:35,kind:'프로모션'},{name:'네이버 기획전',range:'09.20 - 09.28',progress:50,kind:'프로모션'},{name:'신제품 런칭',range:'09.26 - 09.30',progress:10,kind:'상품'}];
const seed=[{id:1,start:18,end:18,name:'상품 선정',project:'10월 가을 선물',kind:'기획'},{id:2,start:21,end:24,name:'디자인팀 요청',project:'10월 가을 선물',kind:'디자인'},{id:3,start:22,end:23,name:'메인 상품 확정',project:'네이버 기획전',kind:'기획'},{id:4,start:25,end:27,name:'배너 1차 확인',project:'10월 가을 선물',kind:'디자인'},{id:5,start:28,end:30,name:'상세페이지 전달',project:'네이버 기획전',kind:'상품등록'}];
export default function Home(){const[view,setView]=useState('calendar'),[events,setEvents]=useState(seed);return <main className="desktop"><section className="finder"><header className="toolbar"><div className="traffic"><i/><i/><i/></div><div className="navArrows">‹　›</div><div className="title">{view.toUpperCase()}</div><div className="tools">◫　⌕　•••</div></header><div className="workspace"><aside className="sidebar"><h5>Favorites</h5><button onClick={()=>setView('project')}>▣　Projects</button><button onClick={()=>setView('task')}>☑　Tasks</button><button className={view==='calendar'?'sideOn':''} onClick={()=>setView('calendar')}>▦　Calendar</button><h5>Channels</h5>{['자사몰','네이버','무신사','에이블리','오늘의집'].map(x=><button key={x}>⌁　{x}</button>)}</aside><section className="pane">{view==='calendar'?<Calendar events={events} setEvents={setEvents}/>:view==='task'?<List items={events}/>:<Projects/>}</section></div><footer className="status"><span>{events.length} tasks</span><span>MINJIN OS　⌁ Notion</span></footer></section></main>}
function Projects(){return <div className="folderGrid">{projects.map(p=><div className="finderItem" key={p.name}><div className="macFolder"><div className="tab"/><div className="paper"/><div className="front"/></div><strong>{p.name}</strong><small>{p.range}</small></div>)}</div>}
function List({items}){return <div className="listView">{items.map(t=><div className="listRow" key={t.id}><span>□　{t.name}</span><span>{t.project}</span><span>{t.kind}</span><span>{t.start}~{t.end}</span></div>)}</div>}
function Calendar({events,setEvents}){const[tab,setTab]=useState('ALL'),[drag,setDrag]=useState(null),[modal,setModal]=useState(null);const visible=tab==='ALL'?events:events.filter(e=>e.project===tab);const cells=Array.from({length:weeks*7},(_,i)=>{const d=i-firstDay+1;return d>=1&&d<=daysInMonth?d:null});const move=day=>{if(!drag||!day)return;setEvents(es=>es.map(e=>{if(e.id!==drag)return e;const len=e.end-e.start;let end=day+len;if(end>daysInMonth){day=Math.max(1,daysInMonth-len);end=daysInMonth}return{...e,start:day,end}}));setDrag(null)};const save=f=>{f={...f,start:Math.max(1,Math.min(daysInMonth,f.start)),end:Math.max(f.start,Math.min(daysInMonth,f.end))};setEvents(es=>f.id?es.map(e=>e.id===f.id?f:e):[...es,{...f,id:Date.now()}]);setModal(null)};return <div className="calendarV3"><div className="calTop"><div className="monthNav"><b>2026년 9월</b><button className="addBtn" onClick={()=>setModal({id:null,name:'',project:projects[0].name,kind:'업무',start:17,end:17})}>＋ 일정</button></div><div className="calTabs">{['ALL',...projects.map(p=>p.name)].map(t=><button className={tab===t?'tabOn':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div></div><div className="week">{['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=><b key={x}>{x}</b>)}</div><div className="calStage"><div className="calGrid" style={{gridTemplateRows:`repeat(${weeks},94px)`}}>{cells.map((d,i)=><div className={'calCell '+(drag?'dropReady':'')} onDoubleClick={()=>d&&setModal({id:null,name:'',project:projects[0].name,kind:'업무',start:d,end:d})} onDragOver={e=>e.preventDefault()} onDrop={()=>move(d)} key={i}>{d&&<span>{String(d).padStart(2,'0')}</span>}</div>)}</div><div className="bars" style={{gridTemplateRows:`repeat(${weeks},94px)`}}>{visible.flatMap(e=>segments(e)).map((s,i)=><div draggable onDragStart={()=>setDrag(s.id)} onDragEnd={()=>setDrag(null)} onDoubleClick={()=>setModal(events.find(e=>e.id===s.id))} className={'rangeBar '+colorClass(s.project)} style={{gridColumn:`${s.colStart}/${s.colEnd}`,gridRow:s.row,marginTop:26+s.lane*19}} key={s.id+'-'+i}>{s.first&&<b>{s.name}</b>}</div>)}</div></div><div className="dragHint">날짜와 기간 막대가 실제 2026년 9월 요일 기준으로 계산됩니다</div>{modal&&<Editor value={modal} onSave={save} onClose={()=>setModal(null)} onDelete={()=>{if(modal.id)setEvents(es=>es.filter(e=>e.id!==modal.id));setModal(null)}}/>}</div>}
function segments(e){let out=[];const startIndex=firstDay+(e.start-1),endIndex=firstDay+(e.end-1);const sw=Math.floor(startIndex/7),ew=Math.floor(endIndex/7);for(let w=sw;w<=ew;w++){const weekStart=w*7,weekEnd=weekStart+6;const from=Math.max(startIndex,weekStart),to=Math.min(endIndex,weekEnd);out.push({...e,row:w+1,colStart:(from%7)+1,colEnd:(to%7)+2,lane:e.id%3,first:from===startIndex})}return out}
function Editor({value,onSave,onClose,onDelete}){const[f,setF]=useState(value);return <div className="modalShade" onMouseDown={onClose}><div className="editor" onMouseDown={e=>e.stopPropagation()}><h3>{f.id?'일정 수정':'새 일정'}</h3><label>일정명<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>프로젝트<select value={f.project} onChange={e=>setF({...f,project:e.target.value})}>{projects.map(p=><option key={p.name}>{p.name}</option>)}</select></label><div className="dates"><label>시작일<input type="number" min="1" max={daysInMonth} value={f.start} onChange={e=>setF({...f,start:+e.target.value})}/></label><label>종료일<input type="number" min={f.start} max={daysInMonth} value={f.end} onChange={e=>setF({...f,end:+e.target.value})}/></label></div><div className="editorBtns">{f.id&&<button className="delete" onClick={onDelete}>삭제</button>}<span/><button onClick={onClose}>취소</button><button className="save" onClick={()=>onSave(f)}>저장</button></div></div></div>}
function colorClass(p){return p==='10월 가을 선물'?'rose':p==='네이버 기획전'?'mint':'lavender'}
